version: '3.7'

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:9.6.24 # latest
    restart: always
    # networks:
    #   netgroup:
    #     ipv4_address: 172.18.0.14
    ports:
    - ${PG_PORT}:5432
    volumes:
      # Just specify a path and let the Engine create a volume
      #- ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - /docker/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    privileged: true
    cap_add:
      - NET_ADMIN
    # env_file:
    #   - postgres.env
    deploy:
      resources:
        limits:
          memory: 2g
# networks:
#   netgroup:
#     name: netgroup
#     driver: bridge
#     attachable: true
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1
  pgadmin:
    image: chorss/docker-pgadmin4
    restart: always
    volumes:
      - /docker/pgadmin:/data
    ports:
      - ${PG_ADMIN_PORT}:5050
    depends_on:
      - postgres
    # env_file:
    #   - postgres.env      
